### ISSUE TITLE
Plugin is empty

### ISSUE THREAD

**Issue by studiopda** [benjaminhoffman/gatsby-plugin-segment-js#1]
Looks like this plugin is missing the gatsby-ssr.js file when pulling down via NPM / Yarn

**Comment by benjaminhoffman** [comment]
hmm weird.  let me take a look.  does it not work for you?  i got it working for me but lemme check.  if there is any output you can share, that would be great.

**Comment by benjaminhoffman** [comment]
working now!  my apologies!  upgrade to  `v2.0.0` !
