### ISSUE TITLE
Question: where does `{ trackPage }` come from?

### ISSUE THREAD

**Issue by i8ramin** [benjaminhoffman/gatsby-plugin-segment-js#15]
Hi. Looking at the source for `gatsby-brower.js`, where exactly does the 2nd paramter `{ trackPage }` come from?

```
exports.onRouteUpdate = ({}, { trackPage }) => {
```

https://github.com/benjaminhoffman/gatsby-plugin-segment-js/blob/master/src/gatsby-browser.js#L1

According to the [Gatsby Browser API docs](https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate), `onRouteUpdate` has only 1 parameter, de-structured as `{ location, prevLocation }`

**Comment by lsirivong** [comment]
Maybe the docs updated since this was posted, but the second parameter is the `pluginOptions` object (aka the object of options in `gatsby-config.js`).

https://github.com/gatsbyjs/gatsby/blob/e9605d5640318c8e30030de08449c30cb420c3a2/packages/gatsby/src/utils/api-browser-docs.js#L66

**Comment by benjaminhoffman** [comment]
haha, tis gatsby!  so many un-published nuances of their API.  things seem to keep changing.

did this solve your Q?  wants to add something into our docs about this? 

i just merged your other PR btw.
