### ISSUE TITLE
No automatic Identify User calls for anonymous visitors

### ISSUE THREAD

**Issue by howardwkim** [benjaminhoffman/gatsby-plugin-segment-js#20]
I am not seeing any `identify` calls in the Segment debugger for anonymous users.
It's my understanding that anonymous users are tracked automatically (Note from Segment):

> Note: You won’t need to call identify for anonymous visitors to your site. We’ll automatically assign them an anonymousId, so just calling page and track will still work just fine without identify.

Is anyone else experiencing this issue? Is this an issue with Gatsby/SSR and Segment?

Additional info:
* I have `trackPage` set to true and it is working
* All the Track events I have added to my Gatsby site are appearing in Segment's debugger
* I don't have any `identify` calls on my site since I do not register/login users, so I rely on the automatic tracking of anonymous users.

**Comment by benjaminhoffman** [comment]
can you share a screenshot of the debugger that shows _no_ identify but _yes_ for track?

bigger question i have is, if everything is functioning as expected and working great, does it really matter that you aren't seeing identify calls?  something could be happening under the hood w/ Segment that we don't know about.

**Comment by howardwkim** [comment]
None of my destinations (Google Analytics, FB, Heap) are receiving events from Segment.
I wanted to eliminate the lack of identify calls as the culprit. 

I'm seeing now that the raw data does include an anonymousId, so the identify call must be done under the hood. Time to search elsewhere... thanks!

Debugger screenshots below.

![identify](https://user-images.githubusercontent.com/8857643/64571513-f3889080-d318-11e9-8996-afecb0e3fd01.png)
![track](https://user-images.githubusercontent.com/8857643/64571514-f3889080-d318-11e9-9a2b-0244aefe622a.png)
