### ISSUE TITLE
Segment JS snippet link returns 404

### ISSUE THREAD

**Issue by catsiller** [benjaminhoffman/gatsby-plugin-segment-js#24]
Segment JS snippet link (https://segment.com/docs/sources/website/analytics.js/quickstart/) returns 404.

**Comment by benjaminhoffman** [comment]
hi @cathysiller thx for pointing this out! :)  

want to update it for me/us via a PR?  here is the correct link i found just now: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/

much appreciated.  no worries if not but lemme know!

**Comment by newhouse** [comment]
Looks like this was fixed in this commit: https://github.com/benjaminhoffman/gatsby-plugin-segment-js/commit/ce80f63c4ee2f907a4b1dbd87534caa540adf5d1
