### ISSUE TITLE
linting and formatting

### ISSUE THREAD

**Issue by TomPridham** [benjaminhoffman/gatsby-plugin-segment-js#36]
i'd like to bring in linting and formatting libraries. do you have a preference?

i'm thinking either https://standardjs.com/ or the one i use at work https://github.com/pdq/eslint-plugin-pdq with prettier. i don't care too much either way. i would just like some tool to catch those small things

**Comment by benjaminhoffman** [comment]
great idea.  +1 on prettier too.

i like the former. standardJS.  not too opinionated here either so whatever you prefer.

**Comment by newhouse** [comment]
I think this is now closed via https://github.com/benjaminhoffman/gatsby-plugin-segment-js/pull/41

I also don't have a strong preference on which style...but it's a nice start.
