### ISSUE TITLE
Update to latest segment snippet V 4.10.0

### ISSUE THREAD

**Issue by mirshko** [benjaminhoffman/gatsby-plugin-segment-js#4]
Theres a new version of the snippet out. its prob worth updating 💯 

https://segment.com/docs/sources/website/analytics.js/quickstart/#step-1-copy-the-snippet

**Comment by ChristoRibeiro** [comment]
@benjaminhoffman what's up about this update?

**Comment by benjaminhoffman** [comment]
i have a few issues / PRs here I need to address.  I will upgrade and release this week.  Promise!

**Comment by benjaminhoffman** [comment]
done & published!  thx for re-pinging me 👍
