### ISSUE TITLE
Will this plugin support segment 2.0?

### ISSUE THREAD

**Issue by collinwu** [benjaminhoffman/gatsby-plugin-segment-js#49]
Hi maintainers,

I appreciate all you do. 🙏 

A concern came up about Segment deprecating v1 of their `analytics.js` library this year? Will this plugin support `analytics.js 2.0`?

Adding link for reference:

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

**Comment by benjaminhoffman** [comment]
i have no plans to unfortunately... unless someone from the community wants to jump in

**Comment by newhouse** [comment]
I'm not sure that there's anything we need to do?

The only call we make is a `page` and the signature for that method does not appear to have changed.

And the docs say the upgrade process is done on the Segment side of things and requires no code changes. I'm guessing the snippet we are including will download whatever version of Analytics that your account key suggests it should.

So, I'm guessing this will just work™️.

**Comment by benjaminhoffman** [comment]
well said @newhouse ... for those reading this, see here how to upgrade: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

it appears there's no required changes on our end

**Comment by collinwu** [comment]
oh interesting. i thought they may have at least changed the script url to `${host}/analytics.js/v1/" + key + "/analytics.min.js` to `${host}/analytics.js/v2/${key}/...`

thank you gentlemen for looking into this more. i should have done so on my part before opening this ticket

🙏

**Comment by newhouse** [comment]
If that turns out not to be the case, please let us know @collinwu

**Comment by collinwu** [comment]
Will do thanks y'all!
