### ISSUE TITLE
Unexpected identifier 'window' 

### ISSUE THREAD

**Issue by eDubrovsky** [benjaminhoffman/gatsby-plugin-segment-js#55]
Hi! I have a problem with the plugin version 4.0.1.

In the console, I get the error: `Uncaught SyntaxError: Unexpected identifier 'window'`

Check image
![image](https://user-images.githubusercontent.com/46897754/208137117-f562bbf7-4b9a-41db-a5bd-bbb7d7b7233f.png)

**Comment by newhouse** [comment]
Hello!  That's odd. What browser and version are you using?

window ought to always be there in a browser.

**Comment by newhouse** [comment]
Nevermind, it's a straight syntax error. Will fix.

**Comment by newhouse** [comment]
@eDubrovsky should be fixed in `v4.0.2`. Can you confirm?

**Comment by eDubrovsky** [comment]
@newhouse, now I get another error:
<img width="1195" alt="CleanShot 2022-12-16 at 22 21 26@2x" src="https://user-images.githubusercontent.com/46897754/208163917-ee36f060-bf6f-400d-83a5-355b3303e33b.png">
<img width="468" alt="CleanShot 2022-12-16 at 22 22 48@2x" src="https://user-images.githubusercontent.com/46897754/208164039-f0b81718-6ee4-45bc-85f1-41340954c381.png">

**Comment by newhouse** [comment]
Ugh. Sorry. Can you try this version: `4.0.3-beta.0`?

**Comment by eDubrovsky** [comment]
Yes, it works! Thanks :)

**Comment by newhouse** [comment]
Great! Sorry about that!
