### ISSUE TITLE
Accessing analytics.track

### ISSUE THREAD

**Issue by bfine9618** [benjaminhoffman/gatsby-plugin-segment-js#8]
Analytics is not found when trying to trigger analytics.track from a page. Do you have example code of this working?

**Comment by djordjevlais** [comment]
Not sure if this is the same issue, but this happened to me before I imported it to the component where I was trying to call it from with: `import analytics from 'gatsby-plugin-segment-js'`

(although another problem appears then, `Property 'track' does not exist` error)

Here's the example page. Any tips? Thanks!

```
import React from 'react'

import Layout from '../components/layout'
import { graphql } from 'gatsby'
import { Flex, Box, Button, Card, Link, Text } from 'rebass'
import getImageFrom from '../utils/get-image'
import analytics from 'gatsby-plugin-segment-js'

const SegmentTest = ({ data: images }) => {
  const getImage = getImageFrom(images)
  return (
    <Layout noHeader={true}>
      <Flex mb={0} pl={20} pr={20} pb={20} bg="#F6F6F6">
        <Text fontSize={[4]} textAlign="center">
          Test
        </Text>

        <Button variant="primary">Claim My Premium Account</Button>
      </Flex>
    </Layout>
  )
}

analytics.track('Segment test page visited', {
  affiliateId: 'Test'
})

export default SegmentTest

```

**Comment by bfine9618** [comment]
Fixed it - i couldnt find the exposed analytics asset in the package. Thank you! 

do we want to update the readme to indicate this?

**Comment by benjaminhoffman** [comment]
@bfine9618 yes please!  would love an update to the README if you have the bandwidth. 👍

**Comment by djordjevlais** [comment]
Hey @bfine9618 just to check, after you imported analytics this way you were able to call `track`? How about `trackPage`?

**Comment by bfine9618** [comment]
So in our production code, i ended up using https://www.npmjs.com/package/@segment/snippet in the ssr page, but i can check. 

@benjaminhoffman it will take me a few days, but happy to update the README, please expect a PR
